#!/usr/bin/env python3
"""
Network Terminal Build Script
Builds the main application executable.

Usage:
    python build.py          # Build the application
    python build.py clean    # Clean build artifacts
    python build.py spec     # Generate spec file only
"""

import subprocess
import sys
import shutil
import platform
from pathlib import Path
from datetime import datetime


class BuildScript:
    """Handles the build process for Network Terminal application."""

    # Application metadata
    APP_NAME = "NetworkTerminal"
    ENTRY_POINT = "main.py"
    VERSION = "1.0.0"

    def __init__(self):
        self.root_dir = Path(__file__).parent
        self.specs_dir = self.root_dir / "specs"
        self.dist_dir = self.root_dir / "dist"
        self.build_dir = self.root_dir / "build"

        # Determine executable extension based on platform
        exe_ext = ".exe" if platform.system() == "Windows" else ""
        self.specs = [
            ("specs/network_terminal.spec", f"{self.APP_NAME}{exe_ext}"),
        ]

        # Path separator for --add-data (Windows uses ';', others use ':')
        self.path_sep = ";" if platform.system() == "Windows" else ":"

    def print_header(self, message):
        """Print a formatted header message."""
        print("\n" + "=" * 70)
        print(f"  {message}")
        print("=" * 70)

    def print_step(self, step_num, total_steps, message):
        """Print a formatted step message."""
        print(f"\n[{step_num}/{total_steps}] {message}")
        print("-" * 70)

    def ensure_spec_file(self):
        """Ensure the spec file exists, creating it if necessary."""
        spec_path = self.root_dir / "specs" / "network_terminal.spec"

        if spec_path.exists():
            return True

        # Create specs directory if needed
        self.specs_dir.mkdir(exist_ok=True)

        print(f"  Creating spec file: {spec_path}")
        return self.generate_spec_file()

    def generate_spec_file(self):
        """Generate the PyInstaller spec file."""
        spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Network Terminal
Auto-generated by build.py
"""

import sys
from pathlib import Path

block_cipher = None

# Determine data separator based on platform
sep = ";" if sys.platform == "win32" else ":"

# Application paths
root_dir = Path(SPECPATH).parent
assets_dir = root_dir / "assets"

a = Analysis(
    ['{self.ENTRY_POINT}'],
    pathex=[str(root_dir)],
    binaries=[],
    datas=[
        (str(assets_dir), 'assets'),
    ],
    hiddenimports=[
        'PyQt6.QtSvg',
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{self.APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window (GUI app)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''
        spec_path = self.specs_dir / "network_terminal.spec"
        try:
            spec_path.write_text(spec_content)
            print(f"  ✓ Created spec file: {spec_path}")
            return True
        except Exception as e:
            print(f"  ✗ Failed to create spec file: {e}")
            return False

    def clean_build_artifacts(self):
        """Remove previous build artifacts."""
        self.print_step(1, 4, "Cleaning previous build artifacts")

        dirs_to_clean = [self.build_dir, self.dist_dir]

        for directory in dirs_to_clean:
            if directory.exists():
                print(f"  Removing: {directory}")
                try:
                    shutil.rmtree(directory)
                    print(f"  ✓ Removed {directory}")
                except Exception as e:
                    print(f"  ⚠ Warning: Could not remove {directory}: {e}")
            else:
                print(f"  • {directory} does not exist (skipping)")

        print("  ✓ Cleanup complete")

    def build_executable(self, spec_file, exe_name, step_num):
        """Build a single executable using PyInstaller."""
        self.print_step(step_num, 4, f"Building {exe_name}")

        spec_path = self.root_dir / spec_file

        if not spec_path.exists():
            print(f"  ✗ ERROR: Spec file not found: {spec_path}")
            return False

        print(f"  Spec file: {spec_file}")
        print(f"  Running PyInstaller...")

        try:
            # Run PyInstaller with the spec file
            result = subprocess.run(
                [sys.executable, "-m", "PyInstaller", str(spec_file)],
                cwd=self.root_dir,
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                print(f"  ✗ PyInstaller failed with return code {result.returncode}")
                print("\n  STDOUT:")
                print(result.stdout)
                print("\n  STDERR:")
                print(result.stderr)
                return False

            # Check if the executable was created
            exe_path = self.dist_dir / exe_name
            if exe_path.exists():
                file_size = exe_path.stat().st_size / (1024 * 1024)  # Convert to MB
                print(f"  ✓ Built successfully: {exe_name} ({file_size:.2f} MB)")
                return True
            else:
                print(f"  ✗ ERROR: Expected output not found: {exe_path}")
                return False

        except Exception as e:
            print(f"  ✗ ERROR: {e}")
            return False

    def verify_outputs(self):
        """Verify that all expected executables were created."""
        self.print_step(4, 4, "Verifying build outputs")

        all_present = True

        for spec_file, exe_name in self.specs:
            exe_path = self.dist_dir / exe_name
            if exe_path.exists():
                file_size = exe_path.stat().st_size / (1024 * 1024)
                print(f"  ✓ {exe_name} ({file_size:.2f} MB)")
            else:
                print(f"  ✗ Missing: {exe_name}")
                all_present = False

        return all_present

    def print_summary(self, success, start_time):
        """Print build summary."""
        end_time = datetime.now()
        duration = (end_time - start_time).total_seconds()

        self.print_header("Build Summary")

        if success:
            print(f"  Status: ✓ SUCCESS")
            print(f"  Duration: {duration:.1f} seconds")
            print(f"  Output directory: {self.dist_dir}")
            print("\n  Built executables:")
            for _, exe_name in self.specs:
                print(f"    • {exe_name}")
        else:
            print(f"  Status: ✗ FAILED")
            print(f"  Duration: {duration:.1f} seconds")
            print("\n  Please check the error messages above.")

        print("=" * 70 + "\n")

    def run(self):
        """Execute the complete build process."""
        self.print_header("Network Terminal Build Process")
        print(f"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"  Python: {sys.version.split()[0]}")
        print(f"  Working directory: {self.root_dir}")

        start_time = datetime.now()

        # Step 1: Clean build artifacts
        self.clean_build_artifacts()

        # Step 2: Ensure spec file exists
        self.print_step(2, 4, "Checking spec file")
        if not self.ensure_spec_file():
            self.print_summary(False, start_time)
            return 1

        # Step 3: Build executable
        build_results = []
        for idx, (spec_file, exe_name) in enumerate(self.specs, start=3):
            result = self.build_executable(spec_file, exe_name, idx)
            build_results.append(result)

        # Step 3: Verify outputs
        verification_passed = self.verify_outputs()

        # Determine overall success
        success = all(build_results) and verification_passed

        # Print summary
        self.print_summary(success, start_time)

        return 0 if success else 1


def main():
    """Main entry point."""
    try:
        builder = BuildScript()

        # Handle command line arguments
        if len(sys.argv) > 1:
            cmd = sys.argv[1].lower()
            if cmd == "clean":
                builder.print_header("Cleaning Build Artifacts")
                builder.clean_build_artifacts()
                print("\n✓ Clean complete\n")
                sys.exit(0)
            elif cmd == "spec":
                builder.print_header("Generating Spec File")
                builder.specs_dir.mkdir(exist_ok=True)
                if builder.generate_spec_file():
                    print("\n✓ Spec file generated\n")
                    sys.exit(0)
                else:
                    sys.exit(1)
            elif cmd in ["-h", "--help", "help"]:
                print(__doc__)
                sys.exit(0)
            else:
                print(f"Unknown command: {cmd}")
                print("Usage: python build.py [clean|spec|help]")
                sys.exit(1)

        # Default: run full build
        exit_code = builder.run()
        sys.exit(exit_code)
    except KeyboardInterrupt:
        print("\n\n⚠ Build interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n✗ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
